# Setup
title:        implicit-RT-triangle
tagline:      implicit-RT-triangle

baseurl:      "/gh-rgn-js"
paginate:     1
locale:       "en"

# About/contact
author:
  name:       grzesiekmq
  url:        



#Others
markdown: kramdown
theme: jekyll-theme-cayman
